functionsDirectory = "C:\\Users\\acer\\Desktop\\protfolio\\my_personal_dashboard\\Project_3DPortfolio-main\\Project_3DPortfolio-main\\netlify\\functions"
functionsDirectoryOrigin = "ui"
headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\acer\\Desktop\\protfolio\\my_personal_dashboard\\Project_3DPortfolio-main\\Project_3DPortfolio-main\\.next"
publishOrigin = "ui"
commandOrigin = "ui"
base = "C:\\Users\\acer\\Desktop\\protfolio\\my_personal_dashboard\\Project_3DPortfolio-main\\Project_3DPortfolio-main"
command = "npm run build"
functions = "C:\\Users\\acer\\Desktop\\protfolio\\my_personal_dashboard\\Project_3DPortfolio-main\\Project_3DPortfolio-main\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]